### ISSUE TITLE
Deploy the sauce demo website so we can see it

### ISSUE THREAD

**Issue by testerremoteee43** [Testerremoteee43SampleOrganisation/saucedemo#1]

**Comment by testerremoteee43** [comment]
its deployed. you can see it here 
https://testerremoteee43sampleorganisation.github.io/saucedemo/

**Comment by Silver88700** [comment]
![sauce](https://github.com/user-attachments/assets/99e120c8-bcbb-4d0a-9ba7-aaba248b1af0)
